server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatIM?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  redis:
    host: 110.42.251.23
    port: 6379
    password: 123456

websocket:
  connector:
    server:
      readIdleSecond: 0
      writeIdleSecond: 0
      allIdleSecond: 360
      sendBuff: -1
      recvBuff: -1
      backlog: 500000
      bossThreads: 1
      connTimeoutMills: 10000
      soLinger: 0
      port: 8080
      reuseAddr: true
      useDirectBuffer: true
      useEpoll: true
      useMemPool: true
      userThreads: 50
      workerThreads: 0
      idleTimes: 5